###
POST http://localhost:1992/api/instruments
Content-Type: application/json

{
        "name": "banane",
        "poids": 1,
        "couleur":"jaune",
        "prix": 6
}

###
GET http://localhost:1992/api/instruments/2

###
PUT http://localhost:1992/api/instruments/3
Content-Type: application/json

{
        "name": "cerise",
        "poids": 0.1,
        "couleur":"rose",
        "prix": 1
}

###
DELETE http://localhost:1992/api/instruments/3




# CREATION DE REQUETE POUR USERS 
###
POST http://localhost:1992/api/users
Content-Type: application/json

{
        "pseudo": "toto",
        "motdpasse": "Azerty1" 
}

###
POST http://localhost:1992/api/users/local
Content-Type: application/json

{
        "pseudo": "toto",
        "motdpasse": "Azerty1" 
}


###
GET http://localhost:1992/api/users

###
PUT http://localhost:1992/api/users
Content-Type: application/json

{
        "pseudo": "toto",
        "motdpasse": "Azerty1" 
}

###
DELETE http://localhost:1992/api/users


# CREATION DE REQUETE POUR REPARATION
###
POST http://localhost:1992/api/reparations
Content-Type: application/json

{
        "name": "soudure",
        "prix": 10
}



###
DELETE http://localhost:1992/api/reparations


